# Generated by Django 3.2.23 on 2024-03-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingridient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingridient',
            new_name='Ingredient',
        ),
    ]
